IF OBJECT_ID('[DDI].[spRefreshMetadata_User_IndexColumns_InsertData]') IS NOT NULL
	DROP PROCEDURE [DDI].[spRefreshMetadata_User_IndexColumns_InsertData];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROCEDURE [DDI].[spRefreshMetadata_User_IndexColumns_InsertData]

AS

DELETE DDI.IndexColumns

DROP TABLE IF EXISTS #IndexColumns

CREATE TABLE #IndexColumns (
    DatabaseName SYSNAME,
    SchemaName SYSNAME,
    TableName SYSNAME,
    IndexName SYSNAME,
    KeyColumnList_Desired VARCHAR(MAX) NOT NULL,
    IncludedColumnList_Desired VARCHAR(MAX) NULL
    PRIMARY KEY NONCLUSTERED (DatabaseName, SchemaName, TableName, IndexName)
    )

INSERT INTO #IndexColumns 
		    (	DatabaseName        , SchemaName	,TableName										,IndexName															, KeyColumnList_Desired																											                                                                            ,IncludedColumnList_Desired																																						)
VALUES	    (	N'PaymentReporting' , N'DataMart'	, N'AgencyLocalityTypeDim'						, N'PK_AgencyLocalityTypeDim'										, N'AgencyLocalityTypeKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'AgencyLocalityTypeDim'						, N'UQ_AgencyLocalityTypeDim'										, N'AgencyLocalityTypeDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'Bai2BankTransactionTypeDim'					, N'PK_Bai2BankTransactionTypeDim'									, N'Bai2BankTransactionTypeKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'Bai2BankTransactionTypeDim'					, N'UQ_Bai2BankTransactionTypeDim'									, N'Bai2BankTransactionTypeDesc ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'BankAccountPurposeDim'						, N'PK_BankAccountPurposeDim'										, N'BankAccountPurposeKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'BankAccountStatusDim'						, N'PK_BankAccountStatusDim'										, N'BankAccountStatusKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'BankAccountStatusDim'						, N'UQ_BankAccountStatusDim'										, N'BankAccountStatusDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'BankAccountTypeDim'							, N'PK_BankAccountTypeDim'											, N'BankAccountTypeKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'BankAccountTypeDim'							, N'UQ_BankAccountTypeDim'											, N'BankAccountTypeDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'BankTransactionTypeDim'						, N'PK_BankTransactionTypeDim'										, N'BankTransactionTypeKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CheckAddModeDim'							, N'PK_CheckAddModeDim'												, N'checkAddModeKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CheckAddModeDim'							, N'UQ_CheckAddModeDim'												, N'checkAddModeDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CheckStatusDim'								, N'PK_CheckStatusDim'												, N'CheckStatusKey ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CheckStatusDim'								, N'UQ_CheckStatusDim'												, N'CheckStatusDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'Company_TaxStatusDim'						, N'PK_Company_TaxStatusDim'										, N'Company_TaxStatusKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'Company_TaxStatusDim'						, N'UDX_Company_TaxStatusDim'										, N'Company_TaxStatusDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CompanyTaxAgencyStatusDim'					, N'PK_CompanyTaxAgencyStatusDim'									, N'CompanyTaxAgencyStatusKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CompanyTaxAgencyStatusDim'					, N'UDX_CompanyTaxAgencyStatusDim'									, N'CompanyTaxAgencyStatusDesc ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CompanyStatusDim'							, N'PK_CompanyStatusDim'											, N'CompanyStatusKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CompanyStatusDim'							, N'UQ_CompanyStatusDim'											, N'CompanyStatusDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CompanyTypeDim'								, N'PK_CompanyTypeDim'												, N'CompanyTypeKey ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CompanyTypeDim'								, N'UQ_CompanyTypeDim'												, N'CompanyTypeDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CreditEffectOnLiabilityDim'					, N'PK_CreditEffectOnLiabilityDim'									, N'CreditEffectOnLiabilityKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'CreditEffectOnLiabilityDim'					, N'UQ_CreditEffectOnLiabilityDim'									, N'CreditEffectOnLiabilityDesc ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'FileRequestProcessingStatusDim'				, N'PK_FileRequestProcessingStatusDim'								, N'FileRequestProcessingStatusKey ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentActionTypeDim'					, N'PK_GarnishmentActionDim'										, N'GarnishmentActionTypeKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentActionTypeDim'					, N'UQ_GarnishmentActionDim'										, N'GarnishmentActionTypeDesc ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentExceptionDim'					, N'PK_GarnishmentExceptionDim'										, N'GarnishmentExceptionKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentExceptionDim'					, N'UQ_GarnishmentExceptionDim'										, N'GarnishmentExceptionDesc ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentIsInArrearsDim'					, N'PK_GarnishmentIsInArrearsDim'									, N'IsInArrearsKey ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentIsInArrearsDim'					, N'UQ_GarnishmentIsInArrearsDim'									, N'IsInArrearsDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentLiabilityStatusDim'				, N'PK_GarnishmentLiabilityStatusDim'								, N'GarnishmentLiabilityStatusKey ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentLiabilityStatusDim'				, N'UQ_GarnishmentLiabilityStatusDim'								, N'GarnishmentLiabilityStatusDesc ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentLiabilityTypeDim'				, N'PK_GarnishmentLiabilityTypeDim'									, N'GarnishmentLiabilityTypeKey ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentMedIndicatorDim'					, N'PK_GarnishmentMedIndicatorDim'									, N'MedIndicatorKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentMedIndicatorDim'					, N'UQ_GarnishmentMedIndicatorDim'									, N'MedIndicatorDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentPayableStatusDim'				, N'PK_GarnishmentPayableStatusDim'									, N'GarnishmentPayableStatusKey ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentPayableStatusDim'				, N'UQ_GarnishmentPayableStatusDim'									, N'GarnishmentPayableStatusDesc ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentPaymentTypeDim'					, N'PK_GarnishmentPaymentTypeDim'									, N'GarnishmentPaymentTypeKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentPaymentTypeDim'					, N'UQ_GarnishmentPaymentTypeDim'									, N'GarnishmentPaymentTypeDesc ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentPayrollInstanceReconStatusDim'	, N'PK_GarnishmentPayrollInstanceReconStatusDim'					, N'GarnishmentPayrollInstanceReconStatusKey ASC'																		                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentPayrollInstanceReconStatusDim'	, N'UQ_GarnishmentPayrollInstanceReconStatusDim'					, N'GarnishmentPayrollInstanceReconStatusDesc ASC'																		                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentsSupportsOthersDim'				, N'PK_GarnishmentsSupportsOthersDim'								, N'SupportsOthersKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentsSupportsOthersDim'				, N'UQ_GarnishmentsSupportsOthersCode'								, N'SupportsOthersDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentStatusDim'						, N'PK_GarnishmentStatusDim'										, N'GarnishmentStatusKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentStatusDim'						, N'UQ_GarnishmentsStatusDim'										, N'GarnishmentStatusDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentTypeDim'							, N'PK_GarnishmentTypeDim'											, N'GarnishmentTypeKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentTypeDim'							, N'UQ_GarnishmentTypeDim'											, N'GarnishmentTypeDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GLAccountClassificationDim'					, N'PK_GLAccountClassificationDim'									, N'GLAccountClassificationKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GLAccountClassificationDim'					, N'UQ_GLAccountClassificationDim'									, N'GLAccountClassificationDesc ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GLAccountStatusDim'							, N'PK_GLAccountStatusDim'											, N'GLAccountStatusKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GLAccountStatusDim'							, N'UQ_GLAccountStatusDim'											, N'GLAccountStatusDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GLAccountTypeDim'							, N'PK_GLAccountTypeDim'											, N'GLAccountTypeKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GLAccountTypeDim'							, N'UQ_GLAccountTypeDim'											, N'GLAccountTypeDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'InboundFileTypeDim'							, N'PK_InboundFileTypeDim'											, N'InboundFileTypeKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'InboundFileTypeDim'							, N'UQ_InboundFileTypeDim'											, N'InboundFileTypeDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'JournalEntryTransactionTypeDim'				, N'PK_JournalEntryTransactionTypeDim'								, N'JournalEntryTransactionTypeDimKey ASC'																				                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'JournalEntryTransactionTypeDim'				, N'UQ_JournalEntryTransactionTypeDim'								, N'JournalEntryTransactionTypeDimDescription ASC'																		                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'LiabilityCollectionPaymentMethodDim'		, N'PK_LiabilityCollectionPaymentMethodDim'							, N'LiabilityCollectionPaymentMethodKey ASC'																			                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'LiabilityCollectionPaymentMethodDim'		, N'UQ_LiabilityCollectionPaymentMethodDim'							, N'LiabilityCollectionPaymentMethodDesc ASC'																			                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'LiabilityCollectionStatusDim'				, N'PK_LiabilityCollectionStatusDim'								, N'LiabilityCollectionStatusKey ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'LiabilityCollectionStatusDim'				, N'UQ_LiabilityCollectionStatusDim'								, N'LiabilityCollectionStatusDesc ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'LiabilityCollectionTypeDim'					, N'PK_LiabilityCollectionTypeDim'									, N'LiabilityCollectionTypeKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'LiabilityStatusDim'							, N'PK_LiabilityStatusDim'											, N'LiabilityStatusKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'LiabilityStatusDim'							, N'UQ_LiabilityStatusDim'											, N'LiabilityStatusDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'LiabilityTypeDim'							, N'PK_LiabilityTypeDim'											, N'LiabilityTypeKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'NettedCollectionStatusDim'					, N'PK_NettedCollectionStatusDim'									, N'NettedCollectionStatusKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'PayExceptionTypeDim'						, N'PK_PayExceptionTypeDim'											, N'PayExceptionTypeKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'PayExceptionTypeDim'						, N'UQ_PayExceptionTypeDim'											, N'PayExceptionTypeDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'PayPortionStateDim'							, N'PK_PayPortionStateDim'											, N'PayPortionStateKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'PayPortionStateDim'							, N'UQ_PayPortionStateDim'											, N'PayPortionStateDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'PayProcessingStatusDim'						, N'PK_PayProcessingStatusDim'										, N'PayProcessingStatusKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'PayProcessingStatusDim'						, N'UQ_PayProcessingStatusDim'										, N'PayProcessingStatusDesc ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'PayrollPaymentStatusDim'					, N'PK_PayrollPaymentStatusDim'										, N'PayrollPaymentStatusKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'PayrollPaymentTypeDim'						, N'PK_PayrollPaymentTypeDim'										, N'PayrollPaymentTypeKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'PayrollTypeDim'								, N'PK_PayrollTypeDim'												, N'PayrollTypeKey ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'PayrollTypeDim'								, N'UQ_PayrollTypeDim'												, N'PayrollTypeDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'ProductActivationStatus'					, N'PK_TenantProductActivationStatus'								, N'ProductActivationStatusKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'ProductActivationStatus'					, N'UQ_TenantProductActivationStatus'								, N'ProductActivationStatusDesc ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'ProductCodeDim'								, N'PK_ProductCodeDim'												, N'ProductCodeKey ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'ProductCodeDim'								, N'UQ_ProductCodeDim'												, N'ProductCodeDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'ProductStatus'								, N'PK_TenantProductStatus'											, N'ProductStatusKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'ProductStatus'								, N'UQ_TenantProductStatus'											, N'ProductStatusDesc ASC'																								                                                                                    , NULL																																											)
            ,(  N'PaymentReporting' , N'DataMart'   , N'QEADJFilterOptions'                         , N'PK_QEADJFilterOptions'                                          , N'QEADJFilterOptionKey ASC'                                                                                                                                                                               , NULL                                                                                                                                                                          )
            ,(  N'PaymentReporting' , N'DataMart'   , N'QEADJFilterOptions'                         , N'UDX_QEADJFilterOption'                                          , N'QEADJFilterOptionDesc ASC'                                                                                                                                                                              , NULL                                                                                                                                                                          )
		    ,(	N'PaymentReporting' , N'DataMart'	, N'RefundPortionDim'							, N'PK_RefundPortionDim'											, N'RefundPortionKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'RefundPortionDim'							, N'UQ_RefundPortionDim'											, N'RefundPortionDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'ReportRequestorTypeDim'						, N'PK_ReportSourceSystemDim'										, N'ReportSourceSystemName ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'ReportRequestStatusDim'						, N'PK_ReportRequestStatusDim'										, N'ReportRequestStatusKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxAgencyTransactionStatusDim'				, N'PK_TaxAgencyTransactionStatusDim'								, N'TaxAgencyTransactionStatusKey ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxAgencyTransactionStatusDim'				, N'UQ_TaxAgencyTransactionStatusDim'								, N'TaxAgencyTransactionStatusDesc ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxCodeActiveStatus'						, N'PK_TaxCodeActiveStatus'											, N'TaxCodeActiveStatusKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxCodeActiveStatus'						, N'UQ_TaxCodeActiveStatus'											, N'TaxCodeActiveStatusDesc ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxCodeProcessingFrequencyDim'				, N'PK_TaxCodeProcessingFrequencyDim'								, N'TaxCodeProcessingFrequencyKey ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxCodeProcessingFrequencyDim'				, N'UQ_TaxCodeProcessingFrequencyDim'								, N'TaxCodeProcessingFrequencyDesc ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxPaymentCreditStatusDim'					, N'PK_TaxPaymentCreditStatusDim'									, N'TaxPaymentCreditStatusKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxPaymentCreditStatusDim'					, N'UQ_TaxPaymentCreditStatusDim'									, N'TaxPaymentCreditStatusDesc ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxPaymentStatusDim'						, N'PK_TaxPaymentStatusDim'											, N'TaxPaymentStatusKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxPaymentStatusDim'						, N'UQ_TaxPaymentStatusDim'											, N'TaxPaymentStatusDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxPaymentTypeDim'							, N'PK_TaxPaymentTypeDim'											, N'TaxPaymentTypeKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxPaymentTypeDim'							, N'UQ_TaxPaymentTypeDim'											, N'TaxPaymentTypeDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TenantStatusDim'							, N'PK_TenantStatusDim'												, N'TenantStatusCode ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TenantStatusDim'							, N'UQ_TenantStatusDim'												, N'TenantStatusDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'UTETaxDataSourceTableSetDim'				, N'PkUTETaxDataSourceTableSetDim'									, N'UTETaxDataSourceTableSetKey ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentActionReasonDim'					, N'PK_GarnishmentActionReasonDim'									, N'GarnishmentActionReasonKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'GarnishmentActionReasonDim'					, N'UQ_GarnishmentActionReasonDim'									, N'GarnishmentActionReasonDesc ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxLiabilityOriginTypeDim'					, N'PK_TaxLiabilityOriginTypeDim'									, N'TaxLiabilityOriginTypeKey ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'TaxLiabilityOriginTypeDim'					, N'UQ_TaxLiabilityOriginTypeDim'									, N'TaxLiabilityOriginTypeDesc ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'YEFileStatusDim'							, N'PK_YEFileStatusDim'												, N'YEFileStatusKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'YEFileStatusDim'							, N'UQ_YEFileStatusDim'												, N'YEFileStatusDesc ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'YEIngestionTypeDim'							, N'PK_YEIngestionTypeDim'											, N'YEIngestionTypeKey ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'YEIngestionTypeDim'							, N'UQ_YEIngestionTypeDim'											, N'YEIngestionTypeDesc ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'YEProcessingStatusDim'						, N'PK_YEProcessingStatusDim'										, N'YEProcessingStatusKey ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'DataMart'	, N'YEProcessingStatusDim'						, N'UQ_YEProcessingStatusDim'										, N'YEProcessingStatusDesc ASC'																							                                                                                    , NULL																																											)
        --	(	DatabaseName        , SchemaName	,TableName									    ,IndexName												            ,KeyColumnList				                                                                                                                                                                                ,IncludedColumnList	                                                                                                                                                            )		
		    ,(	N'PaymentReporting' , N'dbo'		, N'Bai2BankTransactions'						, N'CDX_Bai2BankTransactions'										, N'TransactionSysUtcDt ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Bai2BankTransactions'						, N'PK_Bai2BankTransactions'										, N'TransactionSysUtcDt ASC,BankTransactionId ASC'																		                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'BankAccountDays'							, N'PK_BankAccountDays'												, N'BankAccountDayId ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'BankTransactions'							, N'CDX_BankTransactions'											, N'TransactionUtcDateTime ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'BankTransactions'							, N'IDX_BankTransactions_BankAcctCover'								, N'CollectionId ASC,UpdatedUtcDt ASC,TransactionUtcDateTime ASC'														                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'BankTransactions'							, N'IDX_BankTransactions_GarnishmentPDCover'						, N'TenantId ASC,GarnishmentId ASC,TransactionUtcDateTime ASC'															                                                                                    , N'CbaRoutingNumber4,CbaAccountNumber4,CheckNumber,FileRequestId'																												)
		    ,(	N'PaymentReporting' , N'dbo'		, N'BankTransactions'							, N'PK_BankTransactions'											, N'TransactionUtcDateTime ASC,Id ASC,TenantId ASC'																		                                                                                    , NULL																																											)
		    --,(	N'dbo'		, N'changelog'									, N'PK_changelog'																																						, NULL									                                                                                    																																							, 0			, NULL	
		    ,(	N'PaymentReporting' , N'dbo'		, N'Companies'									, N'IX_Companies'													, N'TenantId ASC,COID ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Companies'									, N'PK_Companies'													, N'CompanyId ASC,TenantId ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Companies'									, N'UQ_Companies'													, N'CompanyId ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Companies'									, N'UQ_Companies_UTEClientId'										, N'UTEClientId ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Company_Tax'								, N'PK_Company_Tax'													, N'Company_TaxGUID'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Company_Tax'								, N'UDX_Company_TaxCompanyId'										, N'CompanyId ASC,TenantId ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Company_Tax'								, N'UDX_Company_TaxId'												, N'Company_TaxId ASC'																							    	                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'CompanyTaxAgency'							, N'PK_CompanyTaxAgency'											, N'CompanyTaxAgencyId ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'CompanyTaxAgency'							, N'UDX_CompanyTaxAgency_Company_TaxGUID_TaxAgencyId'				, N'Company_TaxGUID ASC,TaxAgencyId ASC'																				                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'CompanyProduct'								, N'PK_CompanyProduct'												, N'CompanyId ASC,ProductCodeKey ASC,EffectiveUtcDateFrom ASC'															                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'CustomerBankAccounts'						, N'PK_CustomerBankAccounts'										, N'TenantId ASC,BankAccountId ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'DBDefragLog'								, N'PK_DBDefragLog'													, N'SchemaName ASC,RunDateTime ASC,TableName ASC,IndexName ASC'															                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'EFilingAcknowledgmentAlerts'				, N'PK_EFilingAcknowledgmentAlerts'									, N'EFilingAcknowledgmentAlertId ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'EFilingAcknowledgments'						, N'PK_EFilingAcknowledgments'										, N'SubmissionId ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'EFilingAcknowledgments'						, N'UQ_EFilingAcknowledgments'										, N'EFilingAcknowledgmentId ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'FileRequestPayments'						, N'PK_FileRequestPayments'											, N'PaymentId ASC,PaymentFileRequestId ASC'																				                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'FileRequests'								, N'PK_FileRequests'												, N'FileRequestId ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'GarnishmentLiabilities'						, N'IDX_GarnishmentLiabilities_TenantId'							, N'TenantId ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'GarnishmentLiabilities'						, N'PK_GarnishmentLiabilities'										, N'GarnishmentLiabilityId ASC,TenantId ASC'																			                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'GarnishmentLiabilities'						, N'IDX_GarnishmentLiabilities_PayrollInstanceId'					, N'PayrollInstanceId ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'GarnishmentLiabilities'						, N'UDX_GarnishmentLiabilities'                  					, N'LiabilityId ASC,GarnishmentLiabilityId ASC'																			                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'GarnishmentPayrollInstances'				, N'PK_GarnishmentPayrollInstances'									, N'GarnishmentPayrollInstanceId ASC,TenantId ASC'																		                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'GeneralLedgerAccounts'						, N'IDX_GeneralLedgerAccounts_GLSegment'							, N'GlSegment ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'GeneralLedgerAccounts'						, N'PK_GeneralLedgerAccounts'										, N'AccountId ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'JournalEntries'								, N'CDX_JournalEntries'												, N'TransactionUtcDt ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'JournalEntries'								, N'IDX_JournalEntries_AgencyCode'									, N'AgencyCode ASC,TenantId ASC,TransactionUtcDt ASC'																	                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'JournalEntries'								, N'PK_JournalEntries'												, N'JournalEntryId ASC,TransactionUtcDt ASC'																			                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Liabilities'								, N'IDX_Liabilities_WACDCover'										, N'TenantId ASC,CollectionId ASC,PayrollId ASC,PayUtcDt ASC'															                                                                                    , N'LiabilityId,Type,SourceCreatedUtcDt'																																		)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Liabilities'								, N'CDX_Liabilities'												, N'PayDate ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Liabilities'								, N'IDX_Liabilities_CollectionProductListCover'						, N'CollectionId ASC,ProductCode ASC,PayDate ASC'																		                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Liabilities'								, N'IDX_Liabilities_CompanyAggregateCover'							, N'CollectionId ASC,TenantId ASC,LegalEntityCompanyId ASC,PayDate ASC'													                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Liabilities'								, N'IDX_Liabilities_PayrollAggregateCover'							, N'CollectionId ASC,TenantId ASC,PayrollId ASC,PayDate ASC'															                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Liabilities'								, N'PK_Liabilities'													, N'PayDate ASC,LiabilityId ASC,TenantId ASC'																			                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityCollections'						, N'CDX_LiabilityCollections'										, N'PayUtcDt ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityCollections'						, N'IDX_LiabilityCollections_CDCover'								, N'CollectionId ASC,PayUtcDt ASC'																						                                                                                    , 'CollectedUtcDateTime,Status,Type,ConfirmationNumber,DueDate,PaymentMethod,TenantId'																							)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityCollections'						, N'IDX_LiabilityCollections_WACD_ExternalCover'					, N'TenantId ASC,PayUtcDt ASC'																							                                                                                    , N'CollectionId,PaymentMethod,DueDate,CollectedUtcDateTime,ConfirmationNumber,Status,UsgBankAccountId,CustomerBankAccountId'													)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityCollections'						, N'PK_LiabilityCollections'										, N'PayUtcDt ASC,CollectionId ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityCollections'						, N'IDX_LiabilityCollections_NetCollections'						, N'NettedCollectionId ASC,PayUtcDt ASC'																				                                                                                    , N'CollectionId,ConfirmationNumber,ProcessUtcDate'																																)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityCollections'						, N'IDX_LiabilityCollections_NetCollectionsLatestConfNumberCover'	, N'NettedCollectionId ASC,ProcessUtcDate DESC,PayUtcDt ASC'															                                                                                    , N'ConfirmationNumber'																																							)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityCollections'						, N'IDX_LiabilityCollections_CheckDateCover'	                    , N'CollectedUtcDateTime ASC,PayUtcDt ASC'															                                                                                                        , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityCollections'						, N'IDX_LiabilityCollections_CheckDateCover2'	                    , N'TotalAmount ASC,CollectedUtcDateTime ASC,Type,PayUtcDt ASC'															                                                                                    , NULL      																																									)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityCollectionConfirmationInfos'		, N'PK_LiabilityCollectionConfirmationInfos'						, N'LiabilityCollectionId ASC,ConfirmationInfoId ASC'																	                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityCollectionComments'				, N'PK_LiabilityCollectionComments'									, N'CommentId ASC,LiabilityCollectionId ASC'																			                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityPayments'							, N'PK_LiabilityPayments'											, N'LiabilityId ASC,PaymentId ASC,PaymentLiabilityId ASC'																                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'LiabilityPayments'							, N'IDX_LiabilityPayments_PaymentLiabilityId'						, N'PaymentLiabilityId ASC'																								                                                                                    , N'PaymentId'																																									)
		    ,(	N'PaymentReporting' , N'dbo'		, N'NettedCollections'							, N'PK_NettedCollections'											, N'NettedCollectionId ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'NettedCollectionsLiabilityCollections'		, N'PK_NettedCollectionsLiabilityCollections'						, N'NettedCollectionId ASC,CollectionId ASC'																			                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayActions'									, N'CDX_PayActions'													, N'PayUtcDate ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayActions'									, N'PK_PayActions'													, N'ActionId ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishment_Deductions'					, N'PK_PayGarnishment_Deductions'									, N'PayUtcDate ASC,GarnishmentId ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishment_Employees'					, N'PK_PayGarnishment_Employees'									, N'PayUtcDate ASC,GarnishmentId ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishment_Employees'					, N'IDX_PayGarnishment_Employees_WAPDCover'							, N'EmployeeNumber ASC,PayUtcDate ASC'																					                                                                                    , N'GarnishmentId,FirstName,LastName'																																			)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishment_Payees'						, N'PK_PayGarnishment_Payees'										, N'PayUtcDate ASC,GarnishmentId ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishmentActions'						, N'PK_PayGarnishmentActions'										, N'PayUtcDate ASC,GarnishmentId ASC,ActionId ASC'																		                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishmentActions'						, N'UQ_PayGarnishmentActions'										, N'PayUtcDate ASC,GarnishmentId ASC,ActionId ASC,ActionUtcDateTime ASC'												                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishmentExceptions'					, N'PK_PayGarnishmentExceptions'									, N'PayUtcDate ASC,GarnishmentId ASC,DateCleared ASC,GarnishmentExceptionKey ASC'										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishmentLiabilities'					, N'PK_PayGarnishmentLiabilities'									, N'PayUtcDate ASC,GarnishmentId ASC,GarnishmentLiabilityId ASC,TenantId ASC'											                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishmentLiabilities'					, N'IDX_PayGarnishmentLiabilities_WACDCover'						, N'GarnishmentLiabilityId ASC,PayUtcDate ASC'																			                                                                                    , N'GarnishmentId,Refunded,Removed'																																				)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishments'							, N'IDX_PayGarnishments_CollDetailsCover'							, N'PayUtcDate ASC'																										                                                                                    , N'TenantId,PayId,GarnishmentId,GarnishmentTypeKey,GarnishmentAmount,GarnishmentLiabilityId'																					)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishments'							, N'IDX_PayGarnishments_CollDetailsCover2'							, N'GarnishmentTypeKey ASC,PayUtcDate ASC'																				                                                                                    , N'TenantId,PayId,GarnishmentId,GarnishmentLiabilityId'																														)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishments'							, N'IDX_Paygarnishments_IngestionCover'								, N'GarnishmentId ASC,PayUtcDate ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishments'							, N'IDX_PayGarnishments_WACD_ExternalCover'							, N'TenantId ASC,PayUtcDate ASC'																						                                                                                    , N'PayId,GarnishmentId,GarnishmentTypeKey,GarnishmentAmount,GarnishmentLiabilityId'																							)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishments'							, N'IDX_PayGarnishments_PayrollInstanceId'							, N'PayrollInstanceId ASC,PayUtcDate ASC'																				                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayGarnishments'							, N'PK_PayGarnishments'												, N'PayUtcDate ASC,GarnishmentId ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayLiabilities'								, N'CDX_PayLiabilities'												, N'PayUtcDate ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayLiabilities'								, N'PK_PayLiabilities'												, N'PayUtcDate ASC,PayId ASC,LiabilityId ASC,ActionId ASC'																                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayLiabilities'								, N'IDX_PayLiabilities_LiabilityId'									, N'LiabilityId ASC,IsActive ASC,PayUtcDate ASC'																                                                                                            , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayrollInstances'							, N'PK_PayrollInstances'											, N'PayrollInstanceId ASC,TenantId ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayrollPayments'							, N'PK_PayrollPayments'												, N'PayrollPaymentId ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayrollUnits'								, N'IDX_PayrollUnits_PayGroup'										, N'PayGroup ASC,TenantId ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayrollUnits'								, N'IDX_PayrollUnits_PayrollCode'									, N'PayrollCode ASC'																									                                                                                    , N'PayrollId,TenantId'																																							)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayrollUnits'								, N'IDX_PayrollUnits_TenantId_PayrollCode'							, N'TenantId ASC,PayrollCode ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayrollUnits'								, N'PK_PayrollUnits'												, N'PayrollId ASC,TenantId ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayrollUnits'								, N'UQ_PayrollUnits'												, N'PayrollCode ASC,LegalEntityCompanyId ASC,TenantId ASC'																                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Pays'										, N'CDX_Pays'														, N'PayUtcDate ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Pays'										, N'IDX_Pays_CheckSummaryReportCover'								, N'CompanyId ASC,TenantId ASC,PayId ASC,PayUtcDate ASC'																                                                                                    , N'EmployeeNumber'																																								)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Pays'										, N'IDX_Pays_CDCover'												, N'NetPayLiabilityId ASC,PayUtcDate ASC'																				                                                                                    , N'EmployeeLastName,EmployeeFirstName,EmployeeNumber,CheckNumber,CheckAmount,ddAmount,PayrollId,PayrollInstanceId'																)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Pays'										, N'PK_Pays'														, N'PayId ASC,PayUtcDate ASC'																							                                                                                    , NULL																																											)
        --	(	DatabaseName        , SchemaName	,TableName									    ,IndexName												            ,KeyColumnList				                                                                                                                                                                                ,IncludedColumnList	                                                                                                                                                            )		
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayTaxes'									, N'CDX_PayTaxes'													, N'PayUtcDate ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayTaxes'									, N'IDX_PayTaxes_IngestionCoverWithoutTenantId'						, N'PayId ASC,PayUtcDate ASC'																							                                                                                    , N'UltiTaxCode,DuplicatedLineNumber,ItemNo,TaxAmount,TaxYTDAmount,TaxableWages,TaxableGross,ExemptWages,GrossWages,TaxableTips,SuppTaxAmount,Version,CreatedUtcDt,UpdatedUtcDt')
		    ,(	N'PaymentReporting' , N'dbo'		, N'PayTaxes'									, N'PK_PayTaxes'													, N'PayUtcDate ASC,PayId ASC,UltiTaxCode ASC,DuplicatedLineNumber ASC'													                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'States'										, N'PK_States'														, N'CountryCode ASC,StateCode ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'SystemSettings'								, N'PK_SystemSettings'												, N'SettingName ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAgency'									, N'PK_TaxAgency'													, N'TaxAgencyId ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAgency'									, N'UQ_TaxAgency'													, N'TaxAgencyCode ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAgencyTransactionAmounts'				, N'CDX_TaxAgencyTransactionAmounts'								, N'CheckDate ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAgencyTransactionAmounts'				, N'PK_TaxAgencyTransactionAmounts'									, N'TransactionGUID ASC,TaxId ASC'																						                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAgencyTransactions'						, N'IDX_TaxAgencyTransactions_CollectionDetailsCover'				, N'TaxAgencyId ASC,PostPayrollGUID ASC'																				                                                                                    , N'TransactionAmount,TransactionGUID,TransactionType'																															)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAgencyTransactions'						, N'IDX_TaxAgencyTransactions_IngestionCover'						, N'TransactionGUID ASC,Version ASC'																					                                                                                    , N'TenantId'																																									)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAgencyTransactions'						, N'PK_TaxAgencyTransactions'										, N'TransactionGUID ASC'																					                                                                                                , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAgencyTransactions'						, N'IDX_TaxAgencyTransactions_CDVoidPaymentCover'					, N'TransactionType ASC,PaymentVoidLiabilityId ASC'																		                                                                                    , 'TaxAgencyId,TransactionAmount,PostPayrollId'																																	)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAgencyTransactions'						, N'IDX_TaxAgencyTransactions_TransactionType_CD'					, N'TransactionType ASC'																								                                                                                    , 'TenantId,TaxAgencyId,TransactionGUID,PostPayrollId'																															)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAmounts'									, N'IDX_TaxAmounts_UltiTaxCode'										, N'UltiTaxCode ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAmounts'									, N'PK_TaxAmounts'													, N'TaxPayrollGUID ASC,UTETaxDataSourceTableSetKey ASC,TaxId ASC,TenantId ASC'											                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxAmountsUltiTaxCodes'						, N'PK_TaxAmountsUltiTaxCodes'										, N'TaxPayrollGUID ASC,UTETaxDataSourceTableSetKey ASC,TaxId ASC,UltiTaxCode ASC'										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxCodes'									, N'IDX_TaxCodes_CollectionDetailsCover'							, N'TaxAgencyId ASC'																									                                                                                    , N'TaxId,Description,UTETaxCode,TaxGUID,UltiproTaxCodeList,SortId'																												)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxCodes'									, N'PK_TaxCodes'													, N'TaxId ASC'																											                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxCodes'									, N'UQ_TaxCodes'													, N'TaxGUID ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxLiabilities'								, N'PK_TaxLiabilities'												, N'PayUtcDate ASC,TaxLiabilityId ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxLiabilities'								, N'IDX_TaxLiabilities_CheckDateCover'								, N'TaxLiabilityOriginTypeKey ASC,LiabilityId ASC,PayUtcDate ASC'														                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPaymentCredits'							, N'IDX_TaxPaymentCredits_CollectionDetailsCover'					, N'LiabilityId ASC,TenantId ASC,CreditEffectOnLiabilityKey ASC,CreditAmountApplied ASC,TaxCreditId ASC'				                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPaymentCredits'							, N'IX_TaxPaymentCredits_ReducedQeAdjLiabilityPaymentId'			, N'ReducedQeAdjLiabilityPaymentId ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPaymentCredits'							, N'IX_TaxPaymentCredits_TaxCreditId'								, N'TaxCreditId ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPaymentCredits'							, N'IX_TaxPaymentCredits_TaxPaymentId'								, N'TaxPaymentId ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPaymentCredits'							, N'PK_TaxPaymentCredits'											, N'TaxPaymentCreditId ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPaymentCredits'							, N'UQ_TaxPaymentCredits'											, N'TenantId ASC,SessionId ASC,TaxPaymentId ASC,TaxCreditId ASC,ReducedQeAdjLiabilityPaymentId ASC'						                                                                                    , NULL																																											)		
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPayrolls'								, N'IDX_TaxPayrolls_CollectionDetailsCover'							, N'TenantId ASC,PostPayrollGUID ASC'																					                                                                                    , N'UTETaxDataSourceTableSetKey,ImportUtcDateTime,TaxPayrollGUID,PayrollId'																										)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPayrolls'								, N'IDX_TaxPayrolls_CollectionDetailsCover2'						, N'TenantId ASC,PostPayrollId ASC'																						                                                                                    , N'UTETaxDataSourceTableSetKey,ImportUtcDateTime,TaxPayrollGUID,PayrollId,PayUtcDate'																							)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPayrolls'								, N'PK_TaxPayrolls'													, N'TaxPayrollGUID ASC,UTETaxDataSourceTableSetKey ASC,TenantId ASC'													                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPayrolls'								, N'UQ_TaxPayrolls_PostPayrollGUID'									, N'PostPayrollGUID ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPayrolls'								, N'UQ_TaxPayrolls_PostPayrollId'									, N'PostPayrollId ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxPayrolls'								, N'UDX_TaxPayrolls_CollectionDetailsCover'							, N'PostPayrollGUID ASC'																								                                                                                    , N'UTETaxDataSourceTableSetKey,ImportUtcDateTime,TaxPayrollGUID,PayrollId,LiabilityId'																							)

        --	(	DatabaseName        , SchemaName	,TableName									    ,IndexName												            ,KeyColumnList				                                                                                                                                                                                ,IncludedColumnList	                                                                                                                                                            )		
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxSchedules'								, N'PK_TaxSchedules'										        , N'TaxScheduleGUID ASC'		                                                                                                                                                                            ,NULL				                                                                                                                                                            )
		    ,(	N'PaymentReporting' , N'dbo'		, N'TaxSchedules'								, N'UDX_TaxSchedules_TaxScheduleId'							        , N'TaxScheduleId ASC'			                                                                                                                                                                            ,NULL				                                                                                                                                                            )
		
		    ,(	N'PaymentReporting' , N'dbo'		, N'TenantProduct'								, N'PK_TenantProduct'												, N'TenantId ASC,ProductCodeKey ASC'																					                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'Tenants'									, N'PK_Tenants'														, N'TenantId ASC'																										                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'TenantStatus'								, N'PK_TenantStatus'												, N'TenantId ASC,TenantStatusCode ASC,EffectiveUtcDateFrom ASC,EffectiveUtcDateTo ASC'									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'UltiProTaxCodeMapping'						, N'PK__UltiProTaxCodeMapping'										, N'UltiProTaxCodeMapId ASC'																							                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'UsgBankAccounts'							, N'PK_UsgBankAccounts'												, N'BankAccountId ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'ReportRequests'								, N'PK_ReportRequests'												, N'ReportRequestId ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'ReportParameters'							, N'PK_ReportParameters'											, N'ReportRequestId ASC,ParameterName ASC'																				                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'ReportFileInformation'						, N'PK_ReportFileInformation'										, N'ReportRequestId ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'ReportStatistics'							, N'PK_ReportStatistics'											, N'ReportRequestId ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'ReportObjectStoreInfo'						, N'PK_ReportObjectStoreInfo'										, N'ReportRequestId ASC'																								                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'YEProcessing'								, N'PK_YEProcessing'												, N'YEProcessingId ASC'																									                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'YEProcessing'								, N'UQ_YEProcessing'												, N'ClientId ASC,TaxYear ASC,TenantId ASC'																				                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'YEProcessingFiles'							, N'PK_YEProcessingFiles'											, N'YEProcessingId ASC,InboundFileTypeKey ASC,UltiProAgency ASC'														                                                                                    , NULL																																											)
		    ,(	N'PaymentReporting' , N'dbo'		, N'YEProcessingFiles'							, N'UDX_YEProcessingFiles'											, N'YEProcessingId ASC,FileName ASC'																					                                                                                    , NULL																																											)	

--columnstore
		    ,(  N'PaymentReporting' , N'dbo'		, N'JournalEntries'			                    , N'NCCI_JournalEntries_LedgerBalanceReport'				        , N'JournalEntryId,LiabilityId,TransactionType,Amount,TenantId,AccountId,AccountNumber,TransactionUtcDt,GLSegment,TenantAlias,CompanyId,CompanyCode,PayrollId,PayGroup,ProductCode,StateCode,AgencyCode'	, NULL                                                                                                                                                                          )
            ,(  N'PaymentReporting' , N'dbo'		, N'Liabilities'			                    , N'NCCI_Liabilities_CheckDateCover'	        			        , N'CollectionId,PayDate'	                                                                                                                                                                                , NULL                                                                                                                                                                          )
            ,(  N'PaymentReporting' , N'dbo'		, N'TaxAgencyTransactions'	                    , N'NCCI_TaxAgencyTransactions_PaymentsCount'				        , N'TaxAgencyId,PostPayrollGUID'																																											, NULL                                                                                                                                                                          )
		    ,(  N'PaymentReporting' , N'dbo'		, N'TaxAmounts'				                    , N'NCCI_TaxAmounts_SumByPayroll'							        , N'TenantId,TaxPayrollGUID,UTETaxDataSourceTableSetKey,CurrentAmount'																																		, NULL                                                                                                                                                                          )
		    ,(  N'PaymentReporting' , N'dbo'		, N'TaxPayrolls'			                    , N'NCCI_TaxPayrolls_CheckDateCover'	        			        , N'LiabilityId,PayUtcDate'	                                                                                                                                                                                , NULL                                                                                                                                                                          )
        --	(	DatabaseName        , SchemaName	,TableName									    ,IndexName												            ,KeyColumnList				                                                                                                    ,IncludedColumnList	                                                                                                                                                                                                                                        )		



INSERT INTO DDI.IndexColumns ( DatabaseName ,SchemaName ,TableName ,IndexName ,ColumnName ,IsKeyColumn , KeyColumnPosition, IsIncludedColumn , IncludedColumnPosition, IsFixedSize ,ColumnSize )
SELECT  DatabaseName,
        SchemaName, 
        TableName, 
        IndexName, 
        ColumnName, 
        IsKeyColumn, 
        X.KeyColumnListPosition,
        IsIncludedColumn,
        X.IncludedColumnListPosition,
        IsFixedSize,
        ColumnSize
FROM (  SELECT  AllIdx.DatabaseName, 
                AllIdx.SchemaName, 
                AllIdx.TableName, 
                AllIdx.IndexName, 
                ISNULL(KCL.ColumnName, ICL.ColumnName) AS ColumnName,
                CASE 
                    WHEN KCL.ColumnName IS NOT NULL
                    THEN 1
                    ELSE 0
                END AS IsKeyColumn, 
                KCL.KeyColumnListPosition,
                CASE 
                    WHEN ICL.ColumnName IS NOT NULL
                    THEN 1
                    ELSE 0
                END AS IsIncludedColumn, 
                ICL.IncludedColumnListPosition,
                CASE
                    WHEN ty.name IN ('VARCHAR', 'NVARCHAR', 'TEXT', 'NTEXT', 'VARBINARY', 'FLOAT', 'DECIMAL', 'NUMERIC')
                    THEN 0 
                    ELSE 1
                END AS IsFixedSize,
                c.max_length AS ColumnSize
        --SELECT COUNT(*)
        FROM #IndexColumns AllIdx
            INNER JOIN DDI.SysDatabases d ON AllIdx.DatabaseName = D.name
            INNER JOIN DDI.SysSchemas s ON AllIdx.SchemaName = s.name
            INNER JOIN DDI.SysTables t ON AllIdx.TableName = t.name
                AND s.schema_id = t.schema_id
            INNER JOIN DDI.SysColumns c ON t.object_id = c.object_id
            OUTER APPLY (   SELECT REPLACE(REPLACE(VALUE, ' ASC', ''), ' DESC', '') AS ColumnName, ROW_NUMBER() OVER(PARTITION BY DatabaseName, SchemaName, TableName, IndexName ORDER BY x.MyOrder ASC) AS KeyColumnListPosition
                            FROM (  SELECT value, charindex(value,AllIdx.KeyColumnList_Desired, 0) AS MyOrder 
                                    FROM STRING_SPLIT(AllIdx.KeyColumnList_Desired, ',')) x
                            WHERE REPLACE(REPLACE(VALUE, ' ASC', ''), ' DESC', '') = C.NAME) KCL 
            OUTER APPLY (   SELECT REPLACE(REPLACE(VALUE, ' ASC', ''), ' DESC', '') AS ColumnName, ROW_NUMBER() OVER(PARTITION BY DatabaseName, SchemaName, TableName, IndexName ORDER BY x.MyOrder ASC) AS IncludedColumnListPosition
                            FROM (  SELECT value, charindex(value,AllIdx.IncludedColumnList_Desired, 0) AS MyOrder 
                                    FROM STRING_SPLIT(AllIdx.IncludedColumnList_Desired, ',')) x
                            WHERE REPLACE(REPLACE(VALUE, ' ASC', ''), ' DESC', '') = C.NAME) ICL 
            INNER JOIN DDI.SysTypes ty ON c.user_type_id = ty.user_type_id
        WHERE ty.name NOT IN ('VARCHAR', 'NVARCHAR', 'TEXT', 'NTEXT', 'VARBINARY', 'FLOAT', 'DECIMAL', 'NUMERIC')
            AND ISNULL(KCL.ColumnName, ICL.ColumnName) IS NOT NULL) X

DROP TABLE #IndexColumns

GO
