IF OBJECT_ID('[DOI].[SysIdentityColumns]') IS NULL
CREATE TABLE DOI.SysIdentityColumns (
    [database_id]                           INT NOT NULL,
    [object_id]	                            INT NOT NULL,
    [name]	                                sysname NULL,
    [column_id]	                            INT		NOT NULL,
    [system_type_id]	                    TINYINT	NOT NULL,
    [user_type_id]	                        INT	NOT NULL,
    [max_length]	                        SMALLINT	NOT NULL,
    [precision]	                            TINYINT	NOT NULL,
    [scale]	                                TINYINT	NOT NULL,
    [collation_name]	                    sysname NULL,
    [is_nullable]	                        BIT	NULL,
    [is_ansi_padded]	                    BIT		NOT NULL,
    [is_rowguidcol]	                        bit		NOT NULL,
    [is_identity]	                        bit		NOT NULL,
    [is_filestream]	                        bit		NOT NULL,
    [is_replicated]	                        bit	NULL,
    [is_non_sql_subscribed]	                BIT	NULL,
    [is_merge_published]	                BIT	NULL,
    [is_dts_replicated]	                    bit	NULL,
    [is_xml_document]	                    bit		NOT NULL,
    [xml_collection_id]	                    int		NOT NULL,
    [default_object_id]	                    int		NOT NULL,
    [rule_object_id]	                    int		NOT NULL,
    [seed_value]	                        BIGINT	NULL,
    [increment_value]	                    BIGINT	NULL,
    [last_value]	                        BIGINT NULL,
    [is_not_for_replication]	            bit	NULL,
    [is_computed]	                        BIT		NOT NULL,
    [is_sparse]	                            BIT		NOT NULL,
    [is_column_set]	                        BIT		NOT NULL,
    [generated_always_type]	                TINYINT	NULL,
    [generated_always_type_desc]	        NVARCHAR(120) NULL,
    [encryption_type]	                    INT	NULL,
    [encryption_type_desc]	                NVARCHAR(128) NULL,
    [encryption_algorithm_name]	            NVARCHAR(256) NULL,
    [column_encryption_key_id]	            INT NULL,
    [column_encryption_key_database_name]	NVARCHAR(128) NULL,
    [is_hidden]	                            BIT	NOT NULL,
    [is_masked]	                            BIT	NOT NULL,
    [graph_type]	                        INT	NULL,
    [graph_type_desc]	                    NVARCHAR(120) NULL,
    CONSTRAINT PK_SysIdentityColumns PRIMARY KEY NONCLUSTERED (database_id, object_id, column_id))
WITH
(
MEMORY_OPTIMIZED = ON
)
GO