--@CreateFileGroupsSQL:  
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_2016')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_2016]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201601')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201601]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201602')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201602]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201603')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201603]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201604')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201604]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201605')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201605]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201606')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201606]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201607')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201607]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201608')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201608]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201609')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201609]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201610')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201610]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201611')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201611]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201612')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201612]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_2017')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_2017]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201701')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201701]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201702')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201702]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201703')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201703]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201704')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201704]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201705')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201705]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201706')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201706]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201707')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201707]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201708')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201708]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201709')
BEGIN


	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201709]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201710')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201710]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201711')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201711]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201712')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201712]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_2018')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_2018]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201801')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201801]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201802')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201802]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201803')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201803]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201804')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201804]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201805')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201805]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201806')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201806]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201807')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201807]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201808')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201808]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201809')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201809]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201810')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201810]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201811')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201811]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201812')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201812]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_2019')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_2019]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201901')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201901]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201902')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201902]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201903')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201903]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201904')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201904]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201905')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201905]
END


IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201906')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201906]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201907')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201907]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201908')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201908]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201909')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201909]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201910')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201910]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201911')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201911]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_201912')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_201912]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_2020')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_2020]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202001')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202001]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202002')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202002]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202003')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202003]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202004')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202004]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202005')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202005]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202006')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202006]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202007')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202007]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202008')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202008]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202009')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202009]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202010')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202010]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202011')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202011]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202012')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202012]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_2021')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_2021]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202101')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202101]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202102')
BEGIN


	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202102]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202103')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202103]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202104')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202104]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202105')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202105]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202106')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202106]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202107')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202107]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202108')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202108]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202109')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202109]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202110')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202110]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202111')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202111]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_202112')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_202112]
END
IF NOT EXISTS(SELECT 'True' FROM DOIUnitTests.sys.filegroups WHERE NAME = 'DOIUnitTests_Historical')
BEGIN
	ALTER DATABASE DOIUnitTests ADD FILEGROUP [DOIUnitTests_Historical]
END

--@CreateFilesSQL:  
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_2016')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_2016, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_2016.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_2016
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201601')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201601, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201601.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201601
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201602')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201602, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201602.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201602
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201603')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201603, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201603.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201603
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201604')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201604, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201604.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201604
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201605')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201605, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201605.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201605
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201606')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201606, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201606.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201606
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201607')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201607, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201607.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201607
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201608')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201608, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201608.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201608
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201609')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201609, 


    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201609.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201609
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201610')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201610, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201610.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201610
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201611')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201611, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201611.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201611
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201612')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201612, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201612.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201612
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_2017')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_2017, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_2017.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_2017
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201701')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201701, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201701.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201701
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201702')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201702, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201702.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201702
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201703')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201703, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201703.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201703
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201704')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201704, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201704.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201704
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201705')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201705, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201705.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201705
END


IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201706')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201706, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201706.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201706
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201707')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201707, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201707.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201707
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201708')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201708, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201708.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201708
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201709')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201709, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201709.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201709
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201710')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201710, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201710.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201710
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201711')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201711, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201711.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201711
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201712')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201712, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201712.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201712
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_2018')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_2018, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_2018.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_2018
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201801')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201801, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201801.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201801
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201802')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201802, 


    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201802.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201802
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201803')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201803, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201803.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201803
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201804')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201804, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201804.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201804
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201805')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201805, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201805.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201805
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201806')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201806, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201806.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201806
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201807')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201807, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201807.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201807
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201808')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201808, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201808.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201808
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201809')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201809, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201809.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201809
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201810')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201810, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201810.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201810
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201811')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201811, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201811.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201811
END
IF NOT
 EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201812')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201812, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201812.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201812
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_2019')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_2019, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_2019.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_2019
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201901')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201901, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201901.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201901
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201902')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201902, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201902.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201902
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201903')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201903, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201903.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201903
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201904')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201904, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201904.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201904
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201905')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201905, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201905.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201905
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201906')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201906, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201906.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201906
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201907')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201907, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201907.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201907
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201908')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201908, 


    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201908.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201908
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201909')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201909, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201909.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201909
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201910')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201910, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201910.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201910
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201911')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201911, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201911.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201911
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_201912')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_201912, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_201912.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_201912
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_2020')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_2020, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_2020.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_2020
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202001')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202001, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202001.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202001
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202002')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202002, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202002.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202002
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202003')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202003, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202003.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202003
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202004')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202004, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202004.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202004
END


IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202005')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202005, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202005.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202005
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202006')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202006, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202006.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202006
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202007')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202007, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202007.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202007
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202008')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202008, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202008.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202008
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202009')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202009, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202009.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202009
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202010')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202010, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202010.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202010
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202011')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202011, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202011.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202011
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202012')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202012, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202012.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202012
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_2021')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_2021, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_2021.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_2021
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202101')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202101, 


    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202101.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202101
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202102')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202102, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202102.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202102
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202103')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202103, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202103.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202103
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202104')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202104, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202104.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202104
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202105')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202105, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202105.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202105
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202106')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202106, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202106.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202106
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202107')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202107, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202107.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202107
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202108')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202108, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202108.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202108
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202109')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202109, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202109.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202109
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202110')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202110, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202110.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202110
END
IF NOT
 EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202111')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202111, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202111.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202111
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_202112')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_202112, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_202112.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_202112
END
IF NOT EXISTS(SELECT * FROM DOIUnitTests.sys.database_files WHERE name = 'DOIUnitTests_Historical')
BEGIN
	ALTER DATABASE DOIUnitTests
		ADD FILE 
		(
    		NAME = DOIUnitTests_Historical, 
    		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DOIUnitTests_Historical.ndf', 
			SIZE = 8 MB, 
			MAXSIZE = UNLIMITED, 
			FILEGROWTH = 64 MB
		) 
			TO FILEGROUP DOIUnitTests_Historical
END

