-- <Migration ID="0e69c351-99ec-4d1a-b7c3-6d99d89e015b" TransactionHandling="Custom" />
USE MASTER

EXEC sp_configure 'contained database authentication', 1
RECONFIGURE WITH OVERRIDE
GO


EXEC sp_configure 'user options', 0 ;  
GO  
RECONFIGURE WITH OVERRIDE;  
GO  

IF (DB_ID(N'$(DatabaseName)') IS NULL)
BEGIN
	PRINT N'Creating $(DatabaseName)...';
END
GO	

IF (DB_ID(N'$(DatabaseName)') IS NULL)
BEGIN
	CREATE DATABASE [$(DatabaseName)]
	 CONTAINMENT = PARTIAL
	 ON  PRIMARY 
	( NAME = N'$(DatabaseName)', FILENAME = '[$(DefaultDataPath)]$(DatabaseName).mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
	 LOG ON 
	( NAME = N'$(DatabaseName)_log', FILENAME = '[$(DefaultLogPath)]$(DatabaseName)_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
END
GO



ALTER DATABASE [$(DatabaseName)] SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE [$(DatabaseName)] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [$(DatabaseName)] SET ANSI_NULLS OFF 
ALTER DATABASE [$(DatabaseName)] SET ANSI_PADDING OFF 
ALTER DATABASE [$(DatabaseName)] SET ANSI_WARNINGS OFF 
ALTER DATABASE [$(DatabaseName)] SET ARITHABORT OFF 
ALTER DATABASE [$(DatabaseName)] SET AUTO_CLOSE OFF 
ALTER DATABASE [$(DatabaseName)] SET AUTO_SHRINK OFF 
ALTER DATABASE [$(DatabaseName)] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
ALTER DATABASE [$(DatabaseName)] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [$(DatabaseName)] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [$(DatabaseName)] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [$(DatabaseName)] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [$(DatabaseName)] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [$(DatabaseName)] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [$(DatabaseName)] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [$(DatabaseName)] SET DISABLE_BROKER 
ALTER DATABASE [$(DatabaseName)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [$(DatabaseName)] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [$(DatabaseName)] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [$(DatabaseName)] SET READ_COMMITTED_SNAPSHOT OFF
ALTER DATABASE [$(DatabaseName)] SET READ_WRITE 
ALTER DATABASE [$(DatabaseName)] SET RECOVERY FULL 
ALTER DATABASE [$(DatabaseName)] SET MULTI_USER 
ALTER DATABASE [$(DatabaseName)] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [$(DatabaseName)] SET TARGET_RECOVERY_TIME = 60 SECONDS 
ALTER DATABASE [$(DatabaseName)] SET DELAYED_DURABILITY = DISABLED 
--ALTER DATABASE [$(DatabaseName)] SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT
GO

ALTER DATABASE [$(DatabaseName)] SET DEFAULT_FULLTEXT_LANGUAGE = 1033 
ALTER DATABASE [$(DatabaseName)] SET TRANSFORM_NOISE_WORDS = OFF 
ALTER DATABASE [$(DatabaseName)] SET TWO_DIGIT_YEAR_CUTOFF = 2049 
ALTER DATABASE [$(DatabaseName)] SET DEFAULT_LANGUAGE = 1033 
ALTER DATABASE [$(DatabaseName)] SET NESTED_TRIGGERS = ON 
GO



GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;

IF NOT EXISTS (SELECT name FROM [$(DatabaseName)].sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') 
ALTER DATABASE [$(DatabaseName)] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO


IF NOT EXISTS (SELECT name FROM [$(DatabaseName)].sys.filegroups WHERE name = N'InMem') 
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [InMem] CONTAINS MEMORY_OPTIMIZED_DATA;
GO

IF NOT EXISTS (SELECT 'True' FROM [$(DatabaseName)].sys.database_files WHERE name = N'$(DatabaseName)_InMem')
ALTER DATABASE [$(DatabaseName)] 
    ADD FILE ( NAME = N'$(DatabaseName)_InMem', 
               FILENAME = '$(DefaultDataPath)$(DatabaseName)_InMem.ndf'  ) 
        TO FILEGROUP [InMem]
GO