IF OBJECT_ID('[DDI].[fnNumberTable]') IS NOT NULL
	DROP FUNCTION [DDI].[fnNumberTable];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   FUNCTION [DDI].[fnNumberTable](
	@NumRows INT)

RETURNS TABLE

/*
	SELECT * FROM DDI.fnNumberTable(10)
*/

AS
RETURN
(
	SELECT TOP (@NumRows) ROW_NUMBER() OVER(ORDER BY object_id) AS RowNum
	FROM SYS.OBJECTS
)
GO
