IF OBJECT_ID('[DDI].[fnRefreshMetadataForView]') IS NOT NULL
	DROP FUNCTION [DDI].[fnRefreshMetadataForView];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   FUNCTION [DDI].[fnRefreshMetadataForView](
    @ViewName SYSNAME)

RETURNS VARCHAR(MAX)

AS

/*
    SELECT DDI.fnRefreshMetadataForView('vwPartitionFunctionPartitions')

    NEED TO FIGURE OUT THE ENTIRE DEPENDENCY CHAIN HERE...
    1. FROM VIEW TO SYS METADATA TABLES, 
    2. FROM SYS METADATA TABLES TO SPs THAT UPDATE THE SYS METADATA TABLES
    3. FROM SPs THAT UPDATE THE SYS METADATA TABLES TO THE USER METADATA TABLES THAT HAVE COMPUTED COLUMNS BASED ON SYS METADATA TABLES.
    4. FROM THESE USER METADATA TABLES TO THE UPDATE SPs THAT UPDATE THE COMPUTED COLUMNS

    IN THE TABLE FUNCTION BELOW WE ONLY HAVE THE FIRST 2 OF THE ABOVE 4.
*/

BEGIN
    DECLARE @SQL VARCHAR(MAX) = ''

    SET @SQL = (
    SELECT  'EXEC DDI.' + ReferencedObjectName + CHAR(13) + CHAR(10)
    FROM DDI.fnGetRefreshMetadataSPsForView('vwPartitionFunctionPartitions')
    ORDER BY ReferencedObjectName ASC
    FOR XML PATH, TYPE).value('.', 'nvarchar(max)')

    RETURN @SQL
END

GO
