IF EXISTS(SELECT * FROM sys.databases WHERE name = 'DDI')
BEGIN
    DROP DATABASE DDI
END
GO

CREATE DATABASE [DDI]
 CONTAINMENT = PARTIAL
 ON  PRIMARY 
( NAME = N'DDI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DDI.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DDI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DDI_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO



ALTER DATABASE [DDI] ADD FILEGROUP [InMemory] CONTAINS MEMORY_OPTIMIZED_DATA 
GO
ALTER DATABASE [DDI] SET COMPATIBILITY_LEVEL = 130
ALTER DATABASE [DDI] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [DDI] SET ANSI_NULLS OFF 
ALTER DATABASE [DDI] SET ANSI_PADDING OFF 
ALTER DATABASE [DDI] SET ANSI_WARNINGS OFF 
ALTER DATABASE [DDI] SET ARITHABORT OFF 
ALTER DATABASE [DDI] SET AUTO_CLOSE OFF 
ALTER DATABASE [DDI] SET AUTO_SHRINK OFF 
ALTER DATABASE [DDI] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
ALTER DATABASE [DDI] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [DDI] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [DDI] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [DDI] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [DDI] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [DDI] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [DDI] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [DDI] SET  DISABLE_BROKER 
ALTER DATABASE [DDI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [DDI] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [DDI] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [DDI] SET READ_COMMITTED_SNAPSHOT ON 
ALTER DATABASE [DDI] SET  READ_WRITE 
ALTER DATABASE [DDI] SET RECOVERY FULL 
ALTER DATABASE [DDI] SET  MULTI_USER 
ALTER DATABASE [DDI] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [DDI] SET DEFAULT_FULLTEXT_LANGUAGE = 1033 
ALTER DATABASE [DDI] SET DEFAULT_LANGUAGE = 1033 
ALTER DATABASE [DDI] SET NESTED_TRIGGERS = ON 
ALTER DATABASE [DDI] SET TRANSFORM_NOISE_WORDS = OFF 
ALTER DATABASE [DDI] SET TWO_DIGIT_YEAR_CUTOFF = 2049 
ALTER DATABASE [DDI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
ALTER DATABASE [DDI] SET DELAYED_DURABILITY = DISABLED 
--ALTER DATABASE [DDI] SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT
GO


USE [DDI]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') 
ALTER DATABASE [DDI] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

ALTER DATABASE [DDI] ADD FILEGROUP [InMem] CONTAINS MEMORY_OPTIMIZED_DATA;
GO
ALTER DATABASE [DDI] 
    ADD FILE ( NAME = N'DDI_InMem', 
               FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DDI_InMem.ndf'  ) 
        TO FILEGROUP [InMem]
GO
