PRINT N'Creating schemas'
GO
IF SCHEMA_ID(N'DOI') IS NULL
EXEC sp_executesql N'CREATE SCHEMA [DOI]
AUTHORIZATION [dbo]'
GO
IF SCHEMA_ID(N'Utility') IS NULL
EXEC sp_executesql N'CREATE SCHEMA [Utility]
AUTHORIZATION [dbo]'
GO